### ISSUE TITLE
xblas::gemm taking xscalar<double/...> instead of double for alpha/beta

### ISSUE THREAD

**Issue by wolfv** [QuantStack/xtensor-blas#28]
Hi @JohanMabille / @SylvainCorlay,

I'd like your input on this. Back in the day, I used xscalar<value_type> for alpha and beta as arguments. The reason was, that I was experimenting with some fancy template overload stuff which would automatically detect an xfunction with an xscalar and evaluate to the correct xblas overload if possible (it was experimental).

Now, it's kinda inconvenient to use the API directly (as in #26) as one needs to explicitly use xscalar<double>(123.0) as argument. 

Can we add an automatic conversion constructor (such that one can just pass the number and it get's automatically converted into an xscalar)? Or should we change the interface of the xblas functions to take `value_type&` instead?

Cheers,

Wolf

**Comment by wolfv** [comment]
This is the code I am referring to: https://github.com/QuantStack/xtensor-blas/blob/master/include/xtensor-blas/xblas.hpp#L131

**Comment by JohanMabille** [comment]
`xscalar` already provides a conversion constructor form its value type (since this constructor is not declared as explicit). However `xscalar` should be kept for internal use only, the interface should take `const value_type&`.

Also have a look at `xref` and `xcref` which provide facility for building an `xscalar` from a `value_type&` or a `const value_type&` when you want to keep the `xscalar` to keep a reference on the value instead of making a copy.

And last but not least, if you need to store expressions that can be scalar values or `xtensor` expressions, `xclosure_t` and `const_xclosure_t` should give you the appropriate closure type.

**Comment by wolfv** [comment]
Ok cool! Any opinion if we should put the transpose arguments in front of alpha/beta or the other way around?

**Comment by JohanMabille** [comment]
I don't have a strong opinion about the parameter order, I think it should just be consistent with the one of `gemm`.

**Comment by wolfv** [comment]
Fixed in #29
