### ISSUE TITLE
Trouble finding xtensor-blas in CMakeLists.txt

### ISSUE THREAD

**Issue by juliangaal** [QuantStack/xtensor-blas#54]
I am hardcoding the xtensor-blas path in my CMakeLists.txt right now, which is obviously not ideal.

```cmake
project(KALMANPP)

cmake_minimum_required(VERSION 3.1)

# Set flags and params
set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_FLAGS_DEBUG "-Wall -g -W")

=====>  include_directories(/usr/local/include/xtensor-blas/)  <=====

find_package(XTENSOR REQUIRED)
find_package(BLAS)
find_package(LAPACK)

add_executable(kalmanpp src/Main.cpp)
target_link_libraries(kalmanpp lapack blas)

```

I installed xtensor-blas via cmake, identical to the xtensor. All files seem to be installed correctly, `/usr/local/include/xtensor-blas/` on my Mac. I'm not an expert with CMake, but looking at your [CMakeLists.txt](https://github.com/QuantStack/xtensor-blas/blob/master/CMakeLists.txt), I can't find any "find_package(XTENSOR_BLAS)" or similar. How can I include it in cmake?

Thanks!

**Comment by wolfv** [comment]
Hi Julian,

have you tried `find_package(xtensor-blas REQUIRED)`? It should work.

Then you get the standard `xtensor_blas_INCLUDE_DIRS` and `xtensor_blas_LIBRARIES` (the latter one is unset!).

**Comment by wolfv** [comment]
closing for now. we just fixed some remaining cmake issues. let us know if you still have issues (& feel free to reopen! :)

**Comment by juliangaal** [comment]
Ah, I always tried `find_package(XTENSOR_BLAS ...)` or `find_package(XTENSOR-BLAS ...)` due to xtensor using `find_package(XTENSOR)`. Maybe for consistency, may I suggest, changing it to "XTENSOR-BLAS" in the future?

**Comment by wolfv** [comment]
hmm, to be honest, I think even for xtensor everything *should* be lowercase

`find_package(xtensor)`, `include_directories(${xtensor_INCLUDE_DIR})`  :)

**Comment by juliangaal** [comment]
My CMakeLists.txt

```cmake
project(KALMANCPP)

cmake_minimum_required(VERSION 3.1)

set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_FLAGS_DEBUG "-Wall -g -W")

find_package(XTENSOR REQUIRED)
find_package(xtensor-blas REQUIRED)
find_package(BLAS REQUIRED)
find_package(LAPACK REQUIRED)

include_directories(include)

add_executable(kalman2d src/Kalman2d.cpp)
target_link_libraries(kalman2d lapack blas)
```

works flawlessly! However, all packages are still found when I use `find_package(all_lower_case)`. I thought cmake is case sensitive. Oh well, thanks anyways! Learned something again

**Comment by wolfv** [comment]
sooooo you're actually not really using cmake here :)

you should add `include_directories(${xtensor_INCLUDE_DIRS} ${xtensor_blas_INCLUDE_DIRS})` as well as when linking, link like that: `target_link_libraries(kalman2d ${LAPACK_LIBRARIES} ${BLAS_LIBRARIES})` otherwise you're not using what you get from `find_package`.

Also you can check out what these variables contain by using `message("BLAS: ${BLAS_LIBRARIES}")` which i find helpful for debugging

**Comment by wolfv** [comment]
note the reason why it works right now, is that you install xtensor & xtensor-blas into your system standard include path, therefore it's picked up.
And for BLAS & LAPACK, you probably have these libraries installed into the standard library path which is why it works. But by just doing `target_link_libraries(kalman2d blas lapack)` you only emit `-llapack -lblas` on the command line which doesn't fully qualify which BLAS and lapack lib and can definitly also differ from what you find with cmake.

**Comment by juliangaal** [comment]
great, thanks! Updated my file
